### ISSUE TITLE
1.13.1 Support

### ISSUE THREAD

**Issue by NullCase** [ElmHoe/PVPToggle#3]
Hi @ElmHoe it's great to have an excuse to contact you again.

It looks like PVP toggle works very well in 1.13 except in two situations. In 1.13.1:

1) players cannot shoot themselves while PVP is disabled.
2) players can set other players on fire with flame bows while pvp is disabled.

How much does it cost to fix these two items?

**Comment by NullCase** [comment]
what's interesting to me is that these are the same problems which appeared in 1.12.2

**Comment by NullCase** [comment]
I have re-downloaded the latest release version (just in case I accidentally used the old one).

I'll know for sure tomorrow.

**Comment by ElmHoe** [comment]
resolved in latest build "pvptoggle_1_13_2.jar" - preparing pull request now

**Comment by ElmHoe** [comment]
Please test using this build and provide feedback, thank you!
https://github.com/ElmHoe/PVPToggle/raw/master/PVPToggle_1_13_2.jar

**Comment by NullCase** [comment]
@ElmHoe Thank you so much!

I have tested this today.

1. With PVP off, players are not set on fire by flame bows. (win!)
2. With pvp on, players are correctly set on fire. (win!)
3. However, when PVP is off, players are unable to harm themselves with arrows. 

Still this release is a fantastic improvement. I was able to readd optional PVP today. Thank you.

How can I provide payment for your work?

**Comment by ElmHoe** [comment]
Hey @NullCase ,

No need for payment, I do this in my spare time :)

point 3. Have you tried enabling "AllowSelfHarming" in your configuration file (I really need to rename this to something more politically correct)? 
This option was added so players can hurt themselves with PVP off. :)

**Comment by NullCase** [comment]
Oh! it's in my configuration file. Ok i'll just enable "AllowSelfHarming."

**Comment by ElmHoe** [comment]
No worries, let me know how it goes!

**Comment by NullCase** [comment]
Works!

You get a notification that both players (you and yourself) have pvp disabled. Small thing though.

Thanks for your hard work @ElmHoe
