### ISSUE TITLE
Players not protected in PVPtoggle_BETA (test results)

### ISSUE THREAD

**Issue by NullCase** [ElmHoe/PVPToggle#7]
Plugin runs. No lag.

Plugin does not protect players.

While pvp is off players can be attacked (both with arrows or melee).

**Comment by ElmHoe** [comment]
Merge made, will create a jar file shortly to test this against.

**Comment by NullCase** [comment]
wohoo! Happy holidays ElmHoe!

**Comment by ElmHoe** [comment]
Happy Holidays as well, @NullCase 🎉

**Comment by NullCase** [comment]
It looks like you guys fixed it. Thank you so much @ElmHoe and @GlossyPanther for your hard work.

If you provide me with a way to compensate you financially (paypal works great for me) I'm happy to send you payment for this work.

**Comment by NullCase** [comment]
Thank you again. Your hard work really means a lot to me and I know players in Liberty Minecraft feel the same way.

Have a great week guys.
